### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by stefandanaita** [pfgithub/scpl#61]
Hello! Really cool stuff here. However, given the repository activity, I guess it's not maintained anymore :(

**Comment by pfgithub** [comment]
It isn't. iOS 13 shortcuts has a lot of changes that would make ScPL difficult to upgrade. It is still possible, but I haven't done it yet.

**Comment by stefandanaita** [comment]
Cheers! I hope you'll make it work!

**Comment by RawDawg** [comment]
> It isn't. iOS 13 shortcuts has a lot of changes that would make ScPL difficult to upgrade. It is still possible, but I haven't done it yet.

You might want to put that information in the readme instead of burying it in a closed issue?

**Comment by pfgithub** [comment]
I thought it was somewhere on the website, I guess not. It's on the top of https://scpl.dev now

**Comment by RawDawg** [comment]
Why not put it in the readme.md? People get it from here and waste their time.
