### ISSUE TITLE
Edit ScPL in local Editor App and Import、export ScPL File

### ISSUE THREAD

**Issue by suliveevil** [pfgithub/scpl#63]
Will you consider add function to edit ScPL in local Editor App and Import、export ScPL File at https://editor.scpl.dev/？

**Comment by pfgithub** [comment]
If you use a local editor, you can compile your code using a command. First install node and npm, then run `npm install --global scpl-cli`, then run `scpl <filename.scpl> --qrcode` to compile your code. If you want to use ScPL Editor, it only supports one file so you will have to copy and paste your code into the website.

**Comment by suliveevil** [comment]
Maybe it’s my browser doesn’t support copy and paste (iPadOS Safari).
I will try that in Windows Firefox/Chrome.
Thank you very much.
